# netlify.toml

# Build settings
[build]
  # Directory to change to before starting build
  base = "myportfolio"

  # Command to build your site
  command = "npm run build"

  # Ignored files and directories during build
  ignore = ["backend", ".gitignore"]

# Deploy settings
[build.environment]
  # Specify the Node.js version
  NODE_VERSION = "14"

# Additional settings
[settings]
  # If your project uses npm, you can specify additional environment variables
  # NODE_ENV = "production"

# Redirects and headers configuration
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Uncomment the following lines if you want to use functions
#[[plugins]]
#  package = "@netlify/plugin-functions-core"